-- CayleyWCS 基础表结构。目标库：PostgreSQL 17；测试：H2 PostgreSQL 模式。
-- 约定：标识符小写带引号；标准列 creator/create_time/last_update_time/is_valid/tenant_id 对齐 CayleyWMS。
-- JSON 统一以 text 存储（JacksonTypeHandler 序列化），保证 PG 与 H2 测试双兼容。

-- ===== 认证（移植自 WMS，前缀 wcs_）=====
create table if not exists "wcs_userrole" (
    "id" bigint generated by default as identity primary key,
    "role_name" varchar(512) not null,
    "is_valid" boolean not null default true,
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "tenant_id" bigint not null default 1
);

create table if not exists "wcs_user" (
    "id" bigint generated by default as identity primary key,
    "user_num" varchar(512) not null,
    "user_name" varchar(512) not null,
    "contact_tel" varchar(512) not null default '',
    "user_role" varchar(512) not null default '',
    "sex" varchar(512) not null default '',
    "is_valid" boolean not null default true,
    "auth_string" varchar(512) not null default '',
    "email" varchar(512) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "tenant_id" bigint not null default 1
);

-- ===== 数据字典（协议类型等枚举的单一事实源）=====
create table if not exists "wcs_dict_type" (
    "id" bigint generated by default as identity primary key,
    "type_code" varchar(128) not null,
    "type_name" varchar(256) not null,
    "remark" varchar(512) not null default '',
    "sort" bigint not null default 0,
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

create table if not exists "wcs_dict_item" (
    "id" bigint generated by default as identity primary key,
    "type_code" varchar(128) not null,
    "item_code" varchar(128) not null,
    "item_name" varchar(256) not null,
    "item_value" varchar(512) not null default '',
    "sort" bigint not null default 0,
    "remark" varchar(512) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 协议表（需求 1）=====
create table if not exists "wcs_protocol" (
    "id" bigint generated by default as identity primary key,
    "protocol_code" varchar(128) not null,
    "protocol_name" varchar(256) not null,
    "target_system" varchar(256) not null default '',
    "protocol_type" varchar(64) not null,
    "data_format" text not null default '{}',
    "transport_template" text not null default '{}',
    "version" varchar(64) not null default '1.0',
    "status" varchar(32) not null default 'enabled',
    "remark" varchar(1024) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 协议点位/字段映射（协议数据格式落地，需求 1）=====
create table if not exists "wcs_protocol_point" (
    "id" bigint generated by default as identity primary key,
    "protocol_id" bigint not null,
    "point_group" varchar(64) not null default '',
    "field_name" varchar(128) not null,
    "symbol_name" varchar(256) not null default '',
    "address" varchar(256) not null default '',
    "data_type" varchar(64) not null default 'INT',
    "rw" varchar(2) not null default 'R',
    "value_range" varchar(256) not null default '',
    "scale" numeric(18,6) not null default 1,
    "sort" bigint not null default 0,
    "description" varchar(1024) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 应用信息表（需求 3）=====
create table if not exists "wcs_application" (
    "id" bigint generated by default as identity primary key,
    "app_code" varchar(128) not null,
    "app_name" varchar(256) not null,
    "app_key" varchar(128) not null,
    "app_secret" varchar(256) not null default '',
    "protocol_id" bigint not null,
    "direction" varchar(32) not null default 'downstream',
    "conn_params" text not null default '{}',
    "max_retry" bigint not null default 5,
    "heartbeat_interval_ms" bigint not null default 5000,
    "enabled" boolean not null default true,
    "status" varchar(32) not null default 'idle',
    "remark" varchar(1024) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 故障码表（需求 6）=====
create table if not exists "wcs_fault_code" (
    "id" bigint generated by default as identity primary key,
    "protocol_id" bigint not null,
    "code" bigint not null,
    "level" varchar(32) not null default 'error',
    "name" varchar(256) not null default '',
    "message" varchar(1024) not null default '',
    "suggestion" varchar(2048) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 任务（调度引擎）=====
create table if not exists "wcs_task" (
    "id" bigint generated by default as identity primary key,
    "task_no" varchar(128) not null,
    "app_id" bigint not null,
    "wms_ref" varchar(256) not null default '',
    "task_type" varchar(64) not null default '',
    "take_row" bigint not null default 0,
    "take_column" bigint not null default 0,
    "take_floor" bigint not null default 0,
    "put_row" bigint not null default 0,
    "put_column" bigint not null default 0,
    "put_floor" bigint not null default 0,
    "port_num" bigint not null default 0,
    "priority" bigint not null default 0,
    "status" varchar(32) not null default 'pending',
    "handshake_step" varchar(64) not null default '',
    "error_code" bigint not null default 0,
    "payload" text not null default '{}',
    "dispatch_time" timestamp(6),
    "finish_time" timestamp(6),
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 报警 =====
create table if not exists "wcs_alarm" (
    "id" bigint generated by default as identity primary key,
    "app_id" bigint not null,
    "fault_code" bigint not null default 0,
    "level" varchar(32) not null default 'error',
    "message" varchar(1024) not null default '',
    "suggestion" varchar(2048) not null default '',
    "status" varchar(32) not null default 'raised',
    "raised_time" timestamp(6) not null default current_timestamp,
    "ack_by" varchar(256) not null default '',
    "ack_time" timestamp(6),
    "cleared_time" timestamp(6),
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

-- ===== 连接事件审计 =====
create table if not exists "wcs_connection_log" (
    "id" bigint generated by default as identity primary key,
    "app_id" bigint not null,
    "app_code" varchar(128) not null default '',
    "event" varchar(64) not null default '',
    "state" varchar(64) not null default '',
    "detail" varchar(2048) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "tenant_id" bigint not null default 1
);

-- ===== 报文留存（高频，按需保留/清理）=====
create table if not exists "wcs_message_log" (
    "id" bigint generated by default as identity primary key,
    "app_id" bigint not null,
    "direction" varchar(16) not null default 'read',
    "field_name" varchar(128) not null default '',
    "address" varchar(256) not null default '',
    "raw_value" varchar(512) not null default '',
    "json_payload" text not null default '{}',
    "create_time" timestamp(6) not null default current_timestamp,
    "tenant_id" bigint not null default 1
);

create index if not exists "idx_wcs_dict_item_type" on "wcs_dict_item" ("type_code");
create index if not exists "idx_wcs_protocol_point_pid" on "wcs_protocol_point" ("protocol_id");
create index if not exists "idx_wcs_fault_code_pid_code" on "wcs_fault_code" ("protocol_id", "code");
create index if not exists "idx_wcs_application_key" on "wcs_application" ("app_key");
create index if not exists "idx_wcs_task_app" on "wcs_task" ("app_id", "status");
create index if not exists "idx_wcs_alarm_app" on "wcs_alarm" ("app_id", "status");
create index if not exists "idx_wcs_conn_log_app" on "wcs_connection_log" ("app_id");
create index if not exists "idx_wcs_msg_log_app" on "wcs_message_log" ("app_id", "create_time");
