-- 上下位绑定授权表（安全：阻止越权指挥设备）。
-- 语义：声明「哪个上位调用方(upstream_app) 被授权指挥 哪台下位设备(downstream_app)」。
-- /open/task/dispatch 鉴权链：AppKeyAuthFilter 验签得到 caller=ATTR_APP_ID(证明) → 与 body.appId(声明) 一起查本表，
-- 命中且 enabled 才放行，否则 FORBIDDEN。等值检查(caller==target)即「自绑定」这一特例。
create table if not exists "wcs_app_binding" (
    "id" bigint generated by default as identity primary key,
    "upstream_app_id" bigint not null,          -- 调用方（通常 direction=upstream，如 WMS）
    "downstream_app_id" bigint not null,        -- 目标设备（direction=downstream）
    "scope" varchar(32) not null default 'dispatch',  -- 权限范围：dispatch/read/control（预留细分）
    "enabled" boolean not null default true,
    "remark" varchar(1024) not null default '',
    "creator" varchar(512) not null default '',
    "create_time" timestamp(6) not null default current_timestamp,
    "last_update_time" timestamp(6) not null default current_timestamp,
    "is_valid" boolean not null default true,
    "tenant_id" bigint not null default 1
);

create unique index if not exists "uk_wcs_app_binding_pair"
    on "wcs_app_binding" ("upstream_app_id", "downstream_app_id", "tenant_id");
create index if not exists "idx_wcs_app_binding_up" on "wcs_app_binding" ("upstream_app_id");

-- 种子：为现有每个有效应用建一条「自绑定」(upstream==downstream)。
-- 当前 demo/PALLET01/PALLET_SIM 均以「设备自身 app_key」下发，自绑定保证既有下发与 Postman 闭环不被新校验拦住。
insert into "wcs_app_binding"
    ("upstream_app_id", "downstream_app_id", "scope", "enabled", "remark", "creator", "tenant_id")
select a."id", a."id", 'dispatch', true, '自绑定（兼容 per-device-key 下发）', 'system', a."tenant_id"
from "wcs_application" a
where a."is_valid" = true
  and not exists (
      select 1 from "wcs_app_binding" b
      where b."upstream_app_id" = a."id" and b."downstream_app_id" = a."id" and b."tenant_id" = a."tenant_id"
  );
